[env:esp32s3-n16r8]
platform = espressif32
board = esp32s3box
framework = arduino
monitor_speed = 115200
board_upload.flash_size = 16MB
board_build.partitions = partitions_large_ffat.csv
board_build.filesystem = fatfs
lib_extra_dirs =
    C:/Users/DELL/.platformio/packages/framework-arduinoespressif32/libraries
build_flags =
    -DARDUINO_USB_MODE=1
    -DARDUINO_USB_CDC_ON_BOOT=1
lib_deps =
    lovyan03/LovyanGFX
    paulstoffregen/XPT2046_Touchscreen
    bblanchon/ArduinoJson
    tzapu/WiFiManager
    madhephaestus/ESP32Servo
